#coding: utf-8

COLOR_GREY = '#DDDDDD'
COLOR_LIGHT_GREY = '#eeeeee'
COLOR_LIGHT_RED = '#FF8080'
COLOR_LIGHT_GREEN = '#C4FFA4'
COLOR_LIGHT_PURPLE = '#f4dbff'
COLOR_LIGHT_YELLOW = '#fdffdb'
COLOR_LIGHT_ORANGE = '#ffefb6'
COLOR_LIGHT_PINK = '#ffe4f2'
COLOR_LIGHT_BLUE = '#d1edff'

DEFAULT_CLOSE_LABEL = 'Schließen'
DEFAULT_CANCEL_LABEL = 'Abbrechen'